### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by hayribakici** [rinukkusu/spotify-dart#100]
In order to increase the score of the pub.dev, there should be more documentation. See [here (Provide Documentation)](https://pub.dev/packages/spotify/score).

**Comment by darylhjd** [comment]
yea im struggling to use this library tbh

**Comment by hayribakici** [comment]
@darylhjd in order to get some insight, I would suggest you to check out the files in the [examples](https://github.com/rinukkusu/spotify-dart/tree/master/example) folder and see how the library is used there.

**Comment by hayribakici** [comment]
Closing issue as it was handled by #148
