### ISSUE TITLE
Any plans for supporting Flutter v2 and null safety?

### ISSUE THREAD

**Issue by MagnusJohansson** [rinukkusu/spotify-dart#101]
Most of the packages in my Flutter 2.0/null safety project depends on http 0.13.0 and json_annotation 4.0.0 which conflicts with this packages old/non null safety dependencies.

**Comment by hayribakici** [comment]
I agree, so far, with the latest dart version, I am not able to compile the library. @rinukkusu I think the dependencies should get updated before more issues arise.

**Comment by dagnorland** [comment]
Tried to update to the newest spotify_sdk - but failed massively on serveral depencies. 
Any plans? Would be very much appreciated!
![Screenshot_20210421-192444](https://user-images.githubusercontent.com/27807238/115595625-70dafc00-a2d7-11eb-930a-22869e5178fd.jpg)

**Comment by rinukkusu** [comment]
New version with null safety is on pub.dev
