### ISSUE TITLE
PlaylistSimple missing description field

### ISSUE THREAD

**Issue by fotiDim** [rinukkusu/spotify-dart#108]
According to the Spotify documentation [SimplifiedPlaylistObject](https://developer.spotify.com/documentation/web-api/reference/#object-simplifiedplaylistobject) has a `description` field which currently is not part of the `PlaylistSimple` model. It would be nice to serialize that field and include it in the model.

**Comment by hayribakici** [comment]
@rinukkusu @fotiDim can this issue be closed?

**Comment by fotiDim** [comment]
@hayribakici yes indeed it can be closed
