### ISSUE TITLE
How to use ? how to integrate this library with the "Authorization Code Flow" method of authorization

### ISSUE THREAD

**Issue by moda20** [rinukkusu/spotify-dart#12]
How to use ? how to integrate this library with the "Authorization Code Flow" method of authorization

**Comment by rinukkusu** [comment]
Sorry @moda20 for letting you wait - this feature is not yet merged into master. We have a PR waiting with exactly what you're asking for, but I didn't take/have the time yet, to look at it closely (although I promised it to @chances 😿). I don't know when this will make its way into a release, but it will probably come this year. 😛

**Comment by SergioSanchezMontesUAM** [comment]
How's the implementation of this functionality going? Is there anything we can do to help you @rinukkusu ?

**Comment by ebarnsli** [comment]
Will this code allow the use of the User endpoints. I'm confused how the `/me` endpoint would work without authorization flow. Would be interested in helping.

**Comment by chances** [comment]
@rinukkusu 
> ... but it will probably come this year.

Most definitely! I've been distracted with other projects lately, but I hope to get back to my PR soon. 🤞

@SergioSanchezMontesUAM @ebarnsli

PR #4 has the beginnings of a solution to this issue.

It lets you explicitly supply tokens in both the Implicit Grant and Authorization Code flows to a `SpotifyApiCredentials ` instance. I use these in a project of mine where I authenticate the user with Spotify externally.

**Comment by jobehi** [comment]
Hello, is there any news concerning the RP ?

**Comment by ebarnsli** [comment]
@jobehi  no, i've had PR's open for months with no response. not activity has occurred on this project in a minute :(

**Comment by jifalops** [comment]
I've got this working in my fork by using an `oauth2.Client` for requests, and the client has the user's credentials and will refresh the token when necessary (in theory, I just got it working and haven't figured out the refresh bugs yet). There is a PR (#16) for just setting the accessToken directly, but then it wont be refreshed automatically.

**Comment by rinukkusu** [comment]
Hi @chances and @jifalops, sadly I don't have the time anymore to really put my head into the spotify docs, but if you guys have a working solution, don't hesitate coming forward with a PR.

@chances Is PR #4 in a usable state or are there still missing pieces?

**Comment by rinukkusu** [comment]
We now do have oauth2 implemented with some documentation. How to use will be discussed in issue https://github.com/rinukkusu/spotify-dart/issues/37
