### ISSUE TITLE
Page.isLast causes "Null check operator used on a null value" exception

### ISSUE THREAD

**Issue by volgin** [rinukkusu/spotify-dart#124]
This line in endpoint_paging.dart in Page.isLast at line 47:36 causes an exception:

`bool get isLast => _paging.offset! + _paging.limit! >= _paging.total!;`

Then(quick) solution is to check for null value:

`bool get isLast => (_paging?.offset ?? 0) + _paging.limit! >= _paging.total!;`

I better solution is to make both `_paging.offset` and `_paging.limit` non-nullable, because both have default values.

**Comment by hayribakici** [comment]
@volgin would you like to make a pull request regarding this issue?

**Comment by rinukkusu** [comment]
Thanks for chiming in @volgin and please excuse my late reaction!
Your change has been merged and published in v0.7.3
