### ISSUE TITLE
Can the search return Track instead of SimpleTrack?

### ISSUE THREAD

**Issue by ebarnsli** [rinukkusu/spotify-dart#13]
Track class is actually the data structure that spotify returns yet this library returns the stripped down version SimpleTrack. I lose out on album information from the track when I search and get SimpleTrack. It makes more sense to return Track because you can still seamlessly cast this to a SimpleTrack if you don't require all of the info that Track provides. I'd rather not inherently lose information. 

Thanks for your work :)

**Comment by rinukkusu** [comment]
Hi @ebarnsli,

you're right, the API docs state a full `Track` object for the search endpoint.
Do you want to take a look at it and open a pull request? 😄 

Otherwise I'll fix it tonight (UTC) or tomorrow.

**Comment by ebarnsli** [comment]
It's a one word change. If i can I'll make a PR just to flex that i "contributed" 😂

**Comment by rinukkusu** [comment]
Version `0.1.3+2` has been published on Pub.
Thanks for finding that bug! :smile_cat:
