### ISSUE TITLE
Get cover art image from track

### ISSUE THREAD

**Issue by Klairm** [rinukkusu/spotify-dart#132]
Hey, I've seen that the only option I have to get the cover art would be using `href` prop in the track, but when I try to open the link it gives it returns me this: 
![imagen](https://user-images.githubusercontent.com/40839469/195601555-4eb7d961-51f4-444b-9bf3-52b14d6222de.png)

Do I need a token for a simple thing like getting a track cover art?

**Comment by gutala** [comment]
Yes, you have to authorize. But the Client Credentials Flow is enough for this case https://github.com/rinukkusu/spotify-dart#client-credentials-flow

**Comment by Klairm** [comment]
> Yes, you have to authorize. But the Client Credentials Flow is enough for this case https://github.com/rinukkusu/spotify-dart#client-credentials-flow

I see, but how would I use those instances to pass a token in the GET request?

**Comment by gutala** [comment]
Hm not sure if I understood you correctly. The example you have in your screenshot is returning me the images in the response. 

![grafik](https://user-images.githubusercontent.com/53314501/195995569-c2f69256-5941-4adf-9de9-ffe1c9b51da7.png)

But like mentioned before, you have to provide the token for the GET request. This doesnt work with the basic GET request from the browser. I used Postman in the screenshot, but the library here is taking care of this Authorization handling also.

**Comment by Klairm** [comment]
> Hm not sure if I understood you correctly. The example you have in your screenshot is returning me the images in the response.
> 
> ![grafik](https://user-images.githubusercontent.com/53314501/195995569-c2f69256-5941-4adf-9de9-ffe1c9b51da7.png)
> 
> But like mentioned before, you have to provide the token for the GET request. This doesnt work with the basic GET request from the browser. I used Postman in the screenshot, but the library here is taking care of this Authorization handling also.

Yes, i tried with curl providing a token, but the thing is, shouldn't I be able to do it without token? just with the normal credentials?

**Comment by Klairm** [comment]
Any ideas?

**Comment by rinukkusu** [comment]
Well, to use the API and get information about a track you need to provide some sort of authentication. This works with a token you receive from the authorization flow where you authorize your App to login, but also with the generated token pair from your Spotify Developer page.

To access the album/track images you need to use the CDN urls from the `images` array, not the one from the `href` property:

![grafik](https://user-images.githubusercontent.com/804848/230786822-0c68dd38-f157-4b1d-a87e-3a91679e32a8.png)
