### ISSUE TITLE
Extract `Player` endpoint from `Me`

### ISSUE THREAD

**Issue by hayribakici** [rinukkusu/spotify-dart#139]
In order to properly reflect the spotify API, I suggest to extract the `player` endpoint (with its functionalities such as `shuffle`, `play`, `next` etc.) into its own endpoint `player`, although it shares the same path as `v1/me/`, but ultimatively is a different api context.

This is how I imagine it could look like:

![RLBBJiCm4BpdA_P8XV87LLGau4IaefPpvSQRniAnWzTEgO1_nt7SOfUUTZqp-_Iko39ZNI-BecWa8u9TZK-A3ree2ry5G0baZL07s0tCTiNFMRUMx8GcIEvXr883TQvj9Tuj_g31Yx8tSvG957xQJ61m5DfHn6AH8PY8lGYooqSlQx027YobAJuSkdEDhM7DEpJE65HMdgPqVfHKpJZVwjSOSXcknZZO6_do1xHfxP2q0gk7u57ARJfzh83](https://user-images.githubusercontent.com/3295340/220701802-b0a156b7-166a-42cf-b9db-421d35b6ab0d.png)

Althogh the name of the base class`_MeEndpoint` is not really acurate. It can/should be changed. 

In general, what do you think?

**Comment by rinukkusu** [comment]
Sounds good, probably reflects usage better!
