### ISSUE TITLE
Where is Track.external_ids.isrc?

### ISSUE THREAD

**Issue by zacwolfe** [rinukkusu/spotify-dart#14]
I'm relying on ISRC to identify tracks and noticed that you have omitted the `external_ids` object from the track object.  What was the reasoning behind this?

BTW, congrats and thanks for the excellent library!

**Comment by rinukkusu** [comment]
Good catch, with the serialization library I've used when starting this project it wasn't possible to serialize and deserialize objects of type `Map<i,j>`. Seems `json_serializable` is capable of this - will report back soon :smile:

**Comment by rinukkusu** [comment]
I've added concrete classes for these maps, since in the api docs they state the keys, they use - I think it's more convenient that way instead of using a map object.

**Comment by zacwolfe** [comment]
Fixed in an hour, now that's service!! :)
