### ISSUE TITLE
Spotify short link support to get track - missing

### ISSUE THREAD

**Issue by rakeshparveen5** [rinukkusu/spotify-dart#154]
To get the spotify track we can use the trackId , but now found that the official Spotify mobile app can create short links for the track. Same short links can't interpreted by this package Or please share the methods if there is any support for this.
Thanks

**Comment by rinukkusu** [comment]
For reference can you share how such a shortlink looks like?

**Comment by rakeshparveen5** [comment]
The short link provided by spotify mobile app :  https://spotify.link/hRkBrwub9xb

**Comment by rinukkusu** [comment]
Hmmm, I don't think there is an official API for that at the moment...

**Comment by hayribakici** [comment]
> Hmmm, I don't think there is an official API for that at the moment...
> 
> Edit: after some more research I found this - maybe it helps upvoting this issue https://community.spotify.com/t5/Spotify-for-Developers/Give-us-an-endpoint-to-decode-new-shortened-share-links/td-p/5523686

There is an anwer to this issue (seen in the link). According to this, all what is necessary is to do a `HEAD` request to the shortend link to retrieve a redirected link to the long spotify link (`https://open.spotify.com/...`). However this cannot be done in dart unless the issue dart-lang/http#699 is fixed.

**Comment by tomcruisesfronttooth** [comment]
@hayribakici if you add the following header to your head request: `"User-Agent": "curl/7.79.1"` then Spotify will return the real url of the track/album/whatever. 
 Example: 
`Future<String> getExpandedUri(String url) {
Dio dio = Dio();
    dio.options.followRedirects = true;
    dio.options.maxRedirects = 10;
    Response<void> response = await dio.head(url,
        options: Options(headers: {"User-Agent": "curl/7.79.1"}));
    if (response.statusCode == 200) {
      print(response.statusCode);
      return response.realUri.toString();
    } else {
      throw Exception();
    }
}
`

**Comment by hayribakici** [comment]
I have good news regarding this issue. There is a merged PR in dart-lang/http#1109, that introduces a new class `BaseResponseWithUrl`, which contains a redirected url in the response. I'll remove the blocked label, so this can be feature can be implemented.

**Comment by rinukkusu** [comment]
Maybe it could be used for that as well! I'm really not an oauth expert tbh and glad that this got implemented by community members that seem to know what they are doing :laughing:

**Comment by hayribakici** [comment]
Yeah, I am also no oauth expert 😅
