### ISSUE TITLE
User not registered in the Developer Dashboard

### ISSUE THREAD

**Issue by nzackoya** [rinukkusu/spotify-dart#160]
I'm sure I have my both users registered in the spotify developer account, but running the code below always gets `403 User not registered in the Developer Dashboard`.
Tried clearing cache, storage, removing the app, changing the user agent, but nothing helped. So I assume this is a bug.

```
final spotify = SpotifyApi.fromAuthCodeGrant(grant, responseUri);
      
 final user = await spotify.me.get();
```

**Comment by rinukkusu** [comment]
Seems to be a spotify/user issue.
