### ISSUE TITLE
Add support for "Track's Audio Analysis"

### ISSUE THREAD

**Issue by hyungtaecf** [rinukkusu/spotify-dart#173]
There is the feature "audio analysis" in the Spotify API but I couldn't find it in this package.
https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis

In my case, I wanted to get the tempo (BPM) of the songs. Is there any quick way to do it or any chance for it to be implemented in this package?

**Comment by rinukkusu** [comment]
There is [`spotify.audioAnalysis`](https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/spotify_base.dart#L37).

Should give you the data you need: https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/models/audio_analysis.dart

**Comment by hyungtaecf** [comment]
Thanks! Sorry, I noticed I was checking an earlier version of the package. Thanks for the quick response :)
