### ISSUE TITLE
Refactor signatures of `startOrResume`

### ISSUE THREAD

**Issue by hayribakici** [rinukkusu/spotify-dart#175]
According to @cudajo 's comment in #145 , it got me thinking.

In order to prevent such confusion, I am thinking to add another overloaded method, that only start/resumes tracks. Something like:

```dart
startOrResume(List<String> uris, [int positionMs = 0])
```
and wrapping thi `uris` and `positionMs` into a `StartOrResumeOptions` object. Taking this idea even further, we could then have a method with a scope of `context_uri`'s and one without. @rinukkusu What do you think?

**Comment by rinukkusu** [comment]
Yeah, this makes sense - good idea! We should make life easier for consumers of this library, so just we have to suffer with this awesome API design. :)

**Comment by hayribakici** [comment]
I also find the `startOrResume` pretty confusing. So according to the spotify documentation, you can start playback with a `contextUri` or a list of track `uris`, so far so good. But when you `pause()` and want to resume your playback you still need to call `startOrResume()`, but what happens if you put a different `contextUri` or track `uris`? Would the playback fail or would you just start a different playback context? If it is the latter, I suggest to provide a `resume({deviceId, retrievePlaybackState})` function to seperate the functionalities a bit more. 

So, to sum it up, we would then have:

```dart

@depracated('...')
Future<PlaybackState?> startOrResume(...) {} //now depracated

Future<PlaybackState?> startWithContext({String? deviceId, String contextId = "", Offset? offset) {
...  
  return startOrResume(...);
}

Future<PlaybackState?> startWithUris({String? deviceId, List<String> uris = const [], int positionMs) {
...
  return startOrResume(...);
}

Future<PlaybackState?> resume({String? deviceId, bool retrievePlaybackState = true}) {
  return startOrResume(deviceId, retrievePlaybackState); 
}
```

What do you think @rinukkusu ?

**Comment by rinukkusu** [comment]
I'm with you on that one. Splitting out the different possibilities makes the intent more clear! From what I understand, supplying a new `contextUri` or new `trackUris` should start playback on them instead of resuming, so I think your proposed setup would work well. :+1:
