### ISSUE TITLE
Spotify Client Authentication

### ISSUE THREAD

**Issue by finey-dev** [rinukkusu/spotify-dart#189]
I was wondering if you could please explain to me how i can create the authentication flow within my flutter app (client-side) to get the auth-code to make requests by redirecting the user using url_launcher instead of creating a backend server, i tried using the example_auth.dart, it works fine but when i paste the redirect uri it just stops there nothing is running after that...

**Comment by hayribakici** [comment]
You need to run the `example_auth` through the `run`-tab in vscode:

<img src="https://github.com/rinukkusu/spotify-dart/assets/3295340/2cb80867-8caa-43f4-a5ac-ab3beef7c037" width="300px" ></img>

or run `dart run example/example_auth.dart`.

**Comment by finey-dev** [comment]
I am getting client timeout, and some times invalid auth code exception...

**Comment by hayribakici** [comment]
@finey-dev Could you paste your stacktrace?

**Comment by hayribakici** [comment]
@finey-dev the comment answer your question? Can this issue be closed?
