### ISSUE TITLE
get tracks list from a playlist URI

### ISSUE THREAD

**Issue by pspgt** [rinukkusu/spotify-dart#19]
There's a way to get tracklist from a playlist URI like spotify:playlist:37i9dQZF1DX8wCc28V2cVW or via playlist id  like for ```spotify.tracks.get(trackid)``` ?
i found this package very usefull so thanks for sharing this.

**Comment by jifalops** [comment]
@pspgt You're looking for `spotify.playlists.getTracksByPlaylistId(playlist.id)`

**Comment by pspgt** [comment]
Yeah some kind of , but seems doesn't exist such method on pub.dev version, is this method on branch master on github?

**Comment by jifalops** [comment]
Oh ya know what I merged #16, #17, and #18. I think both 16/17 add it.

**Comment by pspgt** [comment]
Oh nice thanks

**Comment by rinukkusu** [comment]
Hi @pspgt, this is now merged and in v0.2.0 of the pub package.
