### ISSUE TITLE
An album play something else!

### ISSUE THREAD

**Issue by armanleft** [rinukkusu/spotify-dart#194]
If you select Voleuses album from Archive band and play it, other songs will be played! In this picture you can obviously see that Flying song has 4 min length but in the playing part it shows 15 min!

![image](https://github.com/rinukkusu/spotify-dart/assets/14197908/e9d4eddf-d0fd-4fe3-993b-be6b2422ce70)

I try to make this situation with other player and I faced the same issue with this album. I checked the other albums and it seems they are OK. So I guess it happens in specific albums!
I just lay down this issue here if anyone else face it!

**Comment by rinukkusu** [comment]
Can you add the specific album id that creates this problem? How do you start playback?

**Comment by armanleft** [comment]
In this album:
https://open.spotify.com/album/6jqHsGeWuObUroYHFZWgvq

The first song for example:
https://open.spotify.com/track/03J47bwQ0gwGtypd4gT0hI

by search for Album, band or play from liked songs. It always play from Alternative Track Source, that is a different song.

![image](https://github.com/rinukkusu/spotify-dart/assets/14197908/5bc9807d-0420-449e-b7ee-2a6f4644ec7e)

**Comment by rinukkusu** [comment]
I'm not sure, I follow - is this an issue with the software "Spotube" I'm hearing of for the first time? 

Maybe take your issue there: https://github.com/KRTirtho/spotube 🤔

**Comment by armanleft** [comment]
thanks. I will.
