### ISSUE TITLE
Bug: startWithTracks results in error 400

### ISSUE THREAD

**Issue by ILikeRubberDuckies** [rinukkusu/spotify-dart#202]
When calling `player.startWithTracks` the api responds with error `400:"At least one of \"uri\" or \"position\" should be specified"`. This is probably caused by an empty offset-object that is being sent in the request.

Working:
```
{"context_uri":null,"uris":["spotify:track:id..."],"position_ms":0}
```
Resulting in error:
```
{"context_uri":null,"uris":["spotify:track:id..."],"offset":{},"position_ms":0}
```

Might be related to #187

**Comment by hayribakici** [comment]
@ILikeRubberDuckies yes, this is very mich related to #187 . Thank you for pointing this out. Please use the depracated method `playOrResume` for now. I'll take a look at this.
