### ISSUE TITLE
Can not get Album from TrackSample 

### ISSUE THREAD

**Issue by RizanPSTU** [rinukkusu/spotify-dart#21]
I cannot get the album image from tracksample is there any other way or i am doing wrong or this is a bug?

![Screenshot (14)](https://user-images.githubusercontent.com/32144390/66024894-e83f1400-e516-11e9-91a0-1a97454a00af.png)

**Comment by rinukkusu** [comment]
Hi @RizanPSTU, sorry for the late reply - depends on where you're getting your track from. A simple track as the ones you get from the `album.getTracks` endpoint has no `album` property.
