### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mjuszczyk1** [rinukkusu/spotify-dart#22]
I have spotify_io imported like
```dart
import 'package:spotify/spotify_io.dart';
```
Copied the search from the examples directory on this repo
```dart
var credentials =
    new SpotifyApiCredentials(spotifyClientId, spotifyClientSecret);
var spotify = new SpotifyApi(credentials);
var search = await spotify.search
    .get("metallica")
    .first(2)
    .catchError((err) => print((err as SpotifyException).message));
```
And I get a couple errors, the first one seems like a pretty simple fix:

1. `[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_TypeError' is not a subtype of type 'SpotifyException' in type cast` - this error can be fixed by removing the `as SpotifyException` cast. I first solved the issue by simply removing the `catchError` method, which revealed the second bug.
2.
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 5063): #0      SpotifyApi.handleErrors      package:spotify/src/spotify_io.dart:37
E/flutter ( 5063): #1      SpotifyApi._postImpl         package:spotify/src/spotify_io.dart:21
```
I dug into this one a bit, but I'm pretty new to Dart/Flutter in general so I couldn't figure out a fix. I believe I traced it, at least, to a line in endpoint_paging.dart - specifically [line 163](https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/endpoints/endpoint_paging.dart#L163). It seems the `_get` method is where this bug is actually being generated - I can get a breakpoint to hit on `var jsonString = await _api._get(path);`, but if I remove it and add one to the next line (`var map = json.decode(jsonString);`), it never gets hit. I also can't get breakpoints to work in that `_get` method, so I think this is pretty close to where the bug is coming from, but I'm currently stuck scratching my head.

**Comment by mjuszczyk1** [comment]
Figured this out a while ago, forgot to update this.

This can probably be closed, as it's not necessarily a problem with search, per se - the problem was, due to some lazy copy/pasting, I was using `spotifyClientId` for `spotifyClientSecret` so I was getting a 401 error.
The part that could be improved is actually throwing that as an error because it does not appear in a debug console (personally just using VisualStudio Code for running/debugging).

**Comment by rinukkusu** [comment]
I'll release a new package tomorrow, when I'm back on a real computer :)

**Comment by hayribakici** [comment]
@rinukkusu @mjuszczyk1 does the #29 PR solve this issue? Can this be closed?

**Comment by rinukkusu** [comment]
`v0.2.1` with said changes has just been released.
