### ISSUE TITLE
How to play a song?

### ISSUE THREAD

**Issue by jifalops** [rinukkusu/spotify-dart#23]
This package doesn't have this api yet but even when I do it myself I'm left scratching my head on how to play a song. Following the Spotify API reference, I have:

```dart
Future<void> play([String uri]) async {
  if (client != null) {
    try {
      await client.put('https://api.spotify.com/v1/me/player/play', body: {
        'context_uri': uri,
      });
    } on SpotifyException catch (e) {
      print('${e.status}: ${e.message}');
    }
  } else {
    print('No client available.');
  }
}
```

but when I call `spotify.users.currentlyPlaying()` afterwards `player.isPlaying` is always false. Not to mention I have no clue where to get the actual stream so I can pass it to an audio player.

**Comment by rinukkusu** [comment]
Hi, the API doesn't expose any stream from what I know. After calling the `/me/player/play` endpoint, does any spotify instance you have running start playing that song? 🤔
