### ISSUE TITLE
Currently Playing Not Working 

### ISSUE THREAD

**Issue by RizanPSTU** [rinukkusu/spotify-dart#24]
var credentials = SpotifyApiCredentials(_clientId, _clientSecret);
      var spotify = SpotifyApi(credentials);
      var userplay = spotify.users.;
      _now = await userplay.currentlyPlaying();
      
Giving error

**Comment by rinukkusu** [comment]
Hi, what error do you get? Also I think this is possibly fixed now with [this commit by @ebarnsli](https://github.com/rinukkusu/spotify-dart/commit/8cbceee1bec08d1cc8ef7cf861d6193536ac399c).
