### ISSUE TITLE
How to grab user saved songs?

### ISSUE THREAD

**Issue by JesseGansler** [rinukkusu/spotify-dart#25]
Curious on how to use the TracksMe endpoint to properly grab user saved songs to list similar to the example for Metallica.

**Comment by roisnir** [comment]
```final savedTracks = await spotifyApi.tracks.me.saved.all();```
that will return an iterable of TrackSaved objects. If you want an iterable of Track objects you can do it like this:
```final tracks = savedTracks.map((savedTrack) => savedTrack.track);```
note that you will need the user to authenticate for that.

**Comment by rinukkusu** [comment]
Does that answer your question, @JesseGansler?

**Comment by rinukkusu** [comment]
We can re-open if you have any more questions.
