### ISSUE TITLE
possible bug on endpoint_paging

### ISSUE THREAD

**Issue by roisnir** [rinukkusu/spotify-dart#26]
https://github.com/rinukkusu/spotify-dart/blob/dea7bcd504d711bfaefa660d25deb59dc67e3071/lib/src/endpoints/endpoint_paging.dart#L23
I believe defining _paging as <dynamic> instead of <T> is causing "Paging<dynamic>' is not a subtype of type 'Paging<T>'" exceptions when accessing page.metadata
https://github.com/rinukkusu/spotify-dart/blob/dea7bcd504d711bfaefa660d25deb59dc67e3071/lib/src/endpoints/endpoint_paging.dart#L37
I was wondering if is there any reason of defining it as dynamic and whether changing it will break something else

**Comment by rinukkusu** [comment]
Frankly I didn't look into that too deeply and probably overlooked it, when merging that PR. I see no problems with typing it correctly tbh.

**Comment by roisnir** [comment]
Solved with PR merge
