### ISSUE TITLE
me.recentlyPlayed doesn't support parameters, simplifies return data.

### ISSUE THREAD

**Issue by nrubin29** [rinukkusu/spotify-dart#30]
The `me.recentlyPlayed()` function doesn't support the `limit`, `before`, and `after` parameters that Spotify supports, and it returns only the tracks, losing the `playedAt` and `context` values.

I'm planning to submit a PR soon to fix these issues.

**Comment by rinukkusu** [comment]
Hi, about your PR, do you still want to follow up on it? Otherwise I can pull in the relevant changes myself, too.
