### ISSUE TITLE
Spotify client from refresh token

### ISSUE THREAD

**Issue by nrubin29** [rinukkusu/spotify-dart#32]
#28 just landed, and I'd like the ability to create a client from a refresh token. Basically, I have a database with user refresh tokens, and I'd like to take a user's refresh token and construct an API instance using it. Could we add a `SpotifyApiBase.fromRefreshToken()`?

@roisnir

**Comment by roisnir** [comment]
Yes
We can use oauth2 Client and Credentials default constructors to set the regular parametera and the refresh token.
It's important to set Credentials expiration as any date before now, so the client will know to call refresh and then the access token can be set to anything.
https://github.com/dart-lang/oauth2/blob/master/lib/src/client.dart#L87
https://github.com/dart-lang/oauth2/blob/master/lib/src/credentials.dart#L109

**Comment by rinukkusu** [comment]
`v0.2.1` with said changes has just been released.

**Comment by knissophiliac** [comment]
Can you provide SpotifyApi.fromClient() example? I couldn't construct it from previous credentials.

**Comment by rinukkusu** [comment]
cc @roisnir @LeviHassel 
I couldn't find a description or way either - are we supposed to get the credentials [from the spotify class](https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/spotify_base.dart#L120), construct a new `oauth2.Client` and pass that to `SpotifyApi.fromClient(...)`?

**Comment by knissophiliac** [comment]
It says you should save the credentials somewhere (https://github.com/dart-lang/oauth2/blob/master/README.md#client-credentials-grant) and check if we have it (https://github.com/dart-lang/oauth2/blob/master/README.md#authorization-code-grant) then ```
return new oauth2.Client(credentials,
        identifier: identifier, secret: secret);
```

**Comment by knissophiliac** [comment]
I figured out how to do that. I think it's **critical** to have this in the documentation, because almost every user of this package is going to need to **handle previously logged session**.

Here is how I did that:
User will authenticate himself as provided in documentation and then


    SpotifyApiCredentials spotifyApiCredentials =
        await spotifyApi.getCredentials();

    oauth2.Credentials oauthCredentials = oauth2.Credentials(
        spotifyApiCredentials.accessToken,
        refreshToken: spotifyApiCredentials.refreshToken,
        tokenEndpoint: spotifyApiCredentials.tokenEndpoint,
        scopes: [......],
        expiration: spotifyApiCredentials.expiration);

at this point, you should save `oauthCredentials.toJson()` to local storage/file.

and if user rerun the app, we will check the local storage/file.
if user has previous credentials,

      final credentials = SpotifyApiCredentials(
          "your client id",
          "your secret id");

      oauth2.Credentials oauthCredentials =
          oauth2.Credentials.fromJson(spotify_credentialsjson);

      oauth2.Client oauthClient = oauth2.Client(
        oauthCredentials,
        identifier: credentials.clientId, //oauth2 calls it "identifier", spotify calls it "clientId"
        secret: credentials.clientSecret,
      );

      spotifyApi = SpotifyApi.fromClient(oauthClient);

then we can use spotifyApi(without authentication flow) to make requests

**Comment by roisnir** [comment]
Looks good, you are right about that being not so trivial.
What do you about adding methods that shortens this process and/or elaborate README to cover this topic?

**Comment by knissophiliac** [comment]
I think I will be able to do that in following 1-2 days.

**Comment by LeviHassel** [comment]
For anyone following this thread, the recently merged https://github.com/rinukkusu/spotify-dart/pull/64 lets you reconnect to a previously logged in session just by passing your saved credentials into the `SpotifyApi` consutrctor. There's more details in the README.
