### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by hayribakici** [rinukkusu/spotify-dart#37]
Hi,

is there any better documentation on how to use this library through OAuth? It seems like the `README.md` and the code are inconsistent. It would be nice to test certain features I am currently developing before merging.

**Comment by rinukkusu** [comment]
Hi @hayribakici, I've not used it myself, maybe @LeviHassel has some insights and mybe we can update the documentation based on that!

**Comment by LeviHassel** [comment]
Hi @hayribakici, connecting through OAuth is unfortunately not a straightforward process and it took me a long time to figure it out. I might be able to help if you can answer a few questions for me.

1. What inconsistencies are you seeing between the README and the code?
2. Are you trying to connect through the Authorization Code flow? If so, is it the "imaginary" `redirect` and `listen` methods that are tripping you up?
3. What type of application are you using this package for? i.e. Flutter app, Dart Native etc.

**Comment by hayribakici** [comment]
Hi,

thanks for the reply.

1. so in the README it says 
```dart
...
  final requestUri = ...
  return SpotifyApi.fromAuthCodeGrant(WelcomeScreen.grant, requestUri);
```
But in the code `fromAuthCodeGrant()` requires a `responseUri`. So, there was a little confusion there.

2. Yes, I am trying to authorize myself throught the Authorization Code flow. Indeed, the 'imaginary' methods are the problem. I also looked into the OAuth documentation and their example is pretty much the same. :)
It just would be nice to know, what to there exactly.

3. I am not using this library in any application. I created this PR #36 and I just wanted to to test it in the `example.dart`. Since the device API needs Authorization, I stumbled upon the authorization issue.

**Comment by LeviHassel** [comment]
Thanks for all of the info @hayribakici!

I just put up https://github.com/rinukkusu/spotify-dart/pull/41, which addresses the `requestUri`/`responseUri` confusion and should hopefully clear up the auth process a bit. I'm sure it's not as concrete of an example as you were hoping for, but there's not a one-size-fits-all example for connecting through OAuth.

As you can see in https://github.com/dart-lang/oauth2/issues/53, there's plenty of confusion around the imaginary methods in the `oauth2` package as well. One commenter in that thread made https://github.com/Alacon/flutter_oauth2_client, which is _very similar_ to how I do the Authorization Code Flow in my Flutter app. If we made our own version of that repo (something like `flutter_spotify_client`),  we'd be able to quickly test changes like yours.

**Comment by hayribakici** [comment]
Thank you for all the insights @LeviHassel. I'll take a look at this soon.

**Comment by hayribakici** [comment]
@rinukkusu I think this issue can be closed or should I do it?

**Comment by rinukkusu** [comment]
I assume everything is clear for you now - so yes, I'll close it :)
