### ISSUE TITLE
Unable to compile for Web

### ISSUE THREAD

**Issue by thelostmachine** [rinukkusu/spotify-dart#42]
Hi! Thank you so much for this library!

I'm using Flutter 1.15.17 on the beta channel to build web apps. Once I do `import 'package:spotify/spotify.dart'`, I'm introduced to a compiler error

```
Compiler message:
../../../../.pub-cache/hosted/pub.dartlang.org/spotify-0.3.0/lib/src/spotify_mock.dart:26:20: Error: Too few positional arguments: 2 required, 1 given.
    var file = File('test/data/$partialPath.json');
                   ^
Failed to compile application.
```

From delving into the code, I'm seeing that if the app is a web app the package imports `dart:html`, but the `File` constructor in `html` takes two arguments instead of the one given

`factory File(List<Object> fileBits, String fileName, [Map options])`

I could be doing something wrong, so any insight would be very helpful

Thank you again!

**Comment by thelostmachine** [comment]
So I removed the `test` directory and `spotify_mock.dart` while also commenting out the dependency in `spotify.dart`. It works for web now! The issue lies with the test.

**Comment by LeviHassel** [comment]
Hi @thelostmachine, thanks for all of the details on the issue!

Could you try using the branch for https://github.com/rinukkusu/spotify-dart/pull/44 and see if that fixes the problem for you?

**Comment by thelostmachine** [comment]
Ah sorry for the late reply @LeviHassel 
It works beautifully now! Thank you so much!
