### ISSUE TITLE
Issue in getting list of AudioFeatures for multiple trackIds

### ISSUE THREAD

**Issue by rakeshparveen5** [rinukkusu/spotify-dart#45]
When I try to get the audioFeature for single trackId , it works fine.
This code returns correct result and works fine:
var trackFeatures = await spotifyApi.audioFeatures.get("Single 1 spotify id");

But if I try to get list of audioFeatures for multiple trackIds I am getting exception using below code: 
List<String> ids = ["track id 1 from Spotify", "track id 2 from Spotify" ];
var trackFeatures = await spotifyApi.audioFeatures.list(ids);

This is the stacktrace :

 
<img width="1039" alt="Screenshot 2020-04-21 at 8 27 33 PM" src="https://user-images.githubusercontent.com/14840258/79881206-8d1b3300-840e-11ea-8c6d-00b0d35462af.png">

The error is here in audio_features.dart

     Future<Iterable<AudioFeature>> list(Iterable<String> trackIds) async {
        var jsonString = await _api._get('$_path?ids=${trackIds.join(',')}');
        var map = json.decode(jsonString);

    var artistsMap = map['audio-features'] as Iterable<dynamic>;     ----< map is null >---
    return artistsMap.map((m) => AudioFeature.fromJson(m));
  }

**Comment by rakeshparveen5** [comment]
@rinukkusu As I checked the Spotify Api to get audioFeatures for multiple tracksIds, I found that the response returned by this api 

"https://api.spotify.com/v1/audio-features?ids=6tLEIITb7OlqJ5rdAN77xq%2C4e3ZhgKuJz0xBmLbT6j9Pd%2C2c6a5RlXAB4Ab8Tm06n4eZ"

returns json with different key

{
  "audio_features": [
    {
      "danceability": 0.591,
      "energy": 0.922,

In the library's audio_features.dart  , this function 

   Future<Iterable<AudioFeature>> list(Iterable<String> trackIds) 

having this line

    var artistsMap = map['audio-features'] as Iterable<dynamic>;    

So, If we update the key as per api response , its working as expected and providing the correct result.

'audio-features' should be 'audio_features', 


--

**Comment by rinukkusu** [comment]
Hi @rakeshparveen5 - thanks for finding this bug - care to create a PR?

**Comment by rakeshparveen5** [comment]
ok. @rinukkusu I will create a PR 👍

**Comment by rinukkusu** [comment]
Your fix is published in `0.3.1+1` - thanks for helping out! 😃
