### ISSUE TITLE
Example by using recommendations

### ISSUE THREAD

**Issue by Loopex2019** [rinukkusu/spotify-dart#54]
Hi can you provide an example by using spotify recommendation , because i struggle in the mean : 
Here is my code : 
```dart
static Future<List<TrackSimple>> getRecommendations() async {
    try {
      final Recommendations _recommendations =
          await _spotifyApi.recommendations.get(
        limit: 50,
        seedArtists: [],
      );
      final List<TrackSimple> _tracks = _recommendations.tracks;
      return _tracks;
    } catch (e) {
      print(e);
      Fluttertoast.showToast(msg: 'Failed to get Music');
    }
    return null;
  }
```

**Comment by roisnir** [comment]
Hi
Your code is fine except for the empty seedArtists. You must provide at least one seed of either artist, track, or genre.
You can see this in the exception message:
```
Failed assertion: line x pos y: '**seedsNum >= 1** && seedsNum <= 5': Up to 5 seed values may be provided in any combination of seed_artists, seed_tracks and seed_genres.
```
And another tip, when you face problems you can check your requests with Spotify's API reference. [Here](https://developer.spotify.com/console/get-recommendations) you can that your request will produce 400 "invalid request" response with no seeds.
Try adding some seeds and reply if you have more questions.

**Comment by Loopex2019** [comment]
Thanks but I actually don't understand what these seeds are and how can I get them

**Comment by roisnir** [comment]
Those seeds are Spotify IDs.
Each track, artist or other object that you query through Spotify's API has a unique ID that you can use in other queries.
There are many ways to obtain them, depending on what are you trying to do.
For example. if you want to get recommendations based on the current users top songs:
```dart
final topTracks = await spotify.me.topTracks();
  final topTrackIds = topTracks.take(5).map((track)=>track.id).toList();
  final _recommendations = await spotify.recommendations
      .get(limit: 50, seedTracks: topTrackIds,);
  final _tracks = _recommendations.tracks;
```
Explain what your goal is and we could help you more specifically to you problem.

**Comment by Loopex2019** [comment]
Point 1:
My Goal is to provide the user a list of recommended music and then he can search for his own one. 
Point 2 :
I tried running the code above but it showed me this error : 
```
I/flutter ( 3258): FormatException: Unexpected end of input (at character 1)
I/flutter ( 3258):
I/flutter ( 3258): ^
```
Point 3 : 
I have a Question , does the Me Object refer to me or the user ?

**Comment by roisnir** [comment]
1. Then I think you are looking for something like [featured playlists](https://developer.spotify.com/documentation/web-api/reference/browse/get-list-featured-playlists/) or [https://developer.spotify.com/documentation/web-api/reference/browse/get-list-new-releases/](new releases)
2. What authentication method are you using? In order to use the `me` endpoint you should be logged in with a user with the correct scopes (in this case user-top-read)
3. Me refers to the current logged in user.

**Comment by Loopex2019** [comment]
Thanks  for help . I think i choosed the wrong choice . I should use the featured playlists
