### ISSUE TITLE
Spotify Charts API

### ISSUE THREAD

**Issue by Loopex2019** [rinukkusu/spotify-dart#56]
Hi is there a way to access chart data like accessing the top tracks in each country or on a global level ?

**Comment by roisnir** [comment]
There is a category for top lists and you get category's playlists by country.

You can use the console on Spotify's website or the package's `spotifyApi.categories.list()` to get a list of categories, then you can check what is the top lists category id, and then use `spotifyApi.playlists.getByCategoryId(<categoryId>)`.
In those methods, you can specify locale or country.

More information about listing categories:
https://developer.spotify.com/documentation/web-api/reference/browse/get-list-categories/
Mor information about categories playlists:
https://developer.spotify.com/documentation/web-api/reference/browse/get-categorys-playlists/

**Comment by Loopex2019** [comment]
I can get the top category through the `.first()`  :  `final _categories = _spotifyApi.categories.list().first();`
Or by listing them all and the access the first index : `final _categories = await _spotifyApi.categories.list().all();
    final _firstCategory = _categories.toList()[0];`

**Comment by roisnir** [comment]
You shouldn't access the category neither by index nor by .first().
You can't know if the top lists category stays in a constant index.
I would get it by name with _categories.firstWhere

**Comment by Loopex2019** [comment]
Thanks for help i got it but how to get the playlist tracks . I searched the the properties but i couldn't find anything that can get the tracks of the playlist . Except i fount the `tracksLink`  Property. But i don't how what that acually means . Sorry i am new to spotify so i don't much about it .

**Comment by roisnir** [comment]
Try using the API reference and look over the package methods signature to find your solutions.
See Spotify's [object-model](https://developer.spotify.com/documentation/web-api/reference/object-model/) to check properties meanings
And about getting tracks of a playlist, if you'll type `api.playlist.` and hit tab (assuming you're using a proper IDE) you'll see `api.playlists.getTracksByPlaylistId(<playlistId>)`

**Comment by Loopex2019** [comment]
Thanks a lot @roisnir  for help !!
