### ISSUE TITLE
[Error] API rate limit exceeded 

### ISSUE THREAD

**Issue by Loopex2019** [rinukkusu/spotify-dart#57]
Hi i faced an error while fetching music tracks an there is it :
`
E/flutter (  877): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Error Code: 429
E/flutter (  877): API rate limit exceeded
E/flutter (  877): #0      SpotifyApiBase.handleErrors 
package:spotify/src/spotify_base.dart:134
E/flutter (  877): #1      SpotifyApiBase._getImpl 
package:spotify/src/spotify_base.dart:100
E/flutter (  877): <asynchronous suspension>
E/flutter (  877): #2      SpotifyApiBase._get 
package:spotify/src/spotify_base.dart:83
E/flutter (  877): #3      Pages.getPage 
package:spotify/…/endpoints/endpoint_paging.dart:143
E/flutter (  877): #4      Pages.stream.handlePageAndGetNext 
package:spotify/…/endpoints/endpoint_paging.dart:114
E/flutter (  877): #5      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (  877): #6      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (  877): #7      _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (  877): #8      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (  877): #9      Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (  877): #10     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (  877): #11     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (  877): #12     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (  877): #13     Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart)
E/flutter (  877): <asynchronous suspension>
E/flutter (  877): #14     Pages.stream.handlePageAndGetNext 
package:spotify/…/endpoints/endpoint_paging.dart:114
E/flutter (  877): #15     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (  877): #16     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (  877): #17     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (  877): #18     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (  877): #19     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (  877): #20     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (  877): #21     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (  877): #22     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)

E/flutter (  877): #23     Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart)
E/flutter (  877): <asynchronous suspension>
E/flutter (  877): #24     Pages.stream.handlePageAndGetNext 
package:spotify/…/endpoints/endpoint_paging.dart:114
E/flutter (  877): #25     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (  877): #26     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (  877): #27     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (  877): #28     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (  877): #29     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (  877): #30     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (  877): #31     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (  877): #32     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (  877): #33     Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart)
E/flutter (  877): <asynchronous suspension>
E/flutter (  877): #34     Pages.stream.handlePageAndGetNext 
package:spotify/…/endpoints/endpoint_paging.dart:114
E/flutter (  877): #35     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (  877): #36     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (  877): #37     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (  877): #38     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (  877): #39     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (  877): #40     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (  877): #41     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (  877): #42     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (  877): #43     Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart)
E/flutter (  877): <asynchronous suspension>
E/flutter (  877): #44     Pages.stream.handlePageAndGetNext 
package:spotify/…/endpoints/endpoint_paging.dart:114
E/flutter (  877): #45     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (  877): #46     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (  877): #47     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (  877): #48     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (  877): #49     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (  877): #50     Future._completeWithValue
E/flutter (  877): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Error Code: 429
`
Seems like the error is from spotify itself but i don't understand why it occurs , since the spotify api is free and doesn't have limits for calls

**Comment by roisnir** [comment]
It occurs when you send too many requests rapidly. Spotify doesn't limit the number of calls, however, the rate is limited.
Coincidentally I'm added handling such cases (the PR will be posted soon).
Anyway, it shouldn't happen in most cases, maybe you set the limit too small when you use Paging?
can you post your code?

**Comment by Loopex2019** [comment]
Yes here is it : 
```
static Future<String> getCategoriesId(String categoryName) async {
    try {
      final Iterable<Category> _categories =
          await _spotifyApi.categories.list().all();
      final Iterable<Category> _filteredCategory =
          _categories.where((element) => element.name == categoryName);
      final Category _firstCategory = _filteredCategory.toList()[0];
      return _firstCategory.id;
    } catch (e) {
      Fluttertoast.showToast(msg: 'Failed to get category');
    }
    return null;
  }

  static Future<List<PlaylistSimple>> getPlayLists(String categoryName) async {
    try {
      final String _categoryId = await MusicAPI.getCategoriesId(categoryName);
      final Pages<PlaylistSimple> _recommendations =
          _spotifyApi.playlists.getByCategoryId(_categoryId);
      final Iterable<PlaylistSimple> _playLists = await _recommendations.all();
      return _playLists.toList();
    } catch (e) {
      print(e);
      Fluttertoast.showToast(msg: 'Failed to get playlists');
    }
    return null;
  }

  static Future<List<Track>> getRecommendations(String categoryName) async {
    try {
      final List<PlaylistSimple> _playLists =
          await MusicAPI.getPlayLists(categoryName);
      List<Track> _tracks = [];
      for (PlaylistSimple playList in _playLists) {
        _spotifyApi.playlists.getTracksByPlaylistId(playList.id).all().then(
              (value) => _tracks = value.toList(),
            );
      }
      return _tracks;
    } catch (e) {
      print(e);
      Fluttertoast.showToast(msg: 'Failed to get music tracks');
    }
    return null;
  }```

**Comment by roisnir** [comment]
I guess the exception is raised on
```dart
_spotifyApi.playlists.getTracksByPlaylistId(playList.id).all().then(
              (value) => _tracks = value.toList(),
            );
```
due to the requests sent in the for loop. How many playlists `_playlists` contains?
Do you really need to get all the tracks of all of the playlist all in once?

**Comment by Loopex2019** [comment]
I removed the for loop and requested just the first playlist but this error still occurs : 
 `  
 static Future<List<Track>> getRecommendations(String categoryName) async {
    try {
      final List<PlaylistSimple> _playLists =
          await MusicAPI.getPlayLists(categoryName);
      List<Track> _tracks = [];
     
        _spotifyApi.playlists.getTracksByPlaylistId(playList[0].id).all().then(
              (value) => _tracks = value.toList(),
            );
 
      return _tracks;
    } catch (e) {
      print(e);
      Fluttertoast.showToast(msg: 'Failed to get music tracks');
    }

**Comment by roisnir** [comment]
That's pretty weird. add an `await Future.delayed()` for a few seconds between `getPlayLists` and `getTracksByPlaylistId` to check if the exception is raised because they are called one after the other or maybe it raised inside the `.all()` and tell what happened.
And another check, add a `print('sending request')` in `getRecommendations` to make sure there aren't any other loop the calls this function.
If this problem continues after those checks, the PR should solve it.
