### ISSUE TITLE
Added "market" parameter

### ISSUE THREAD

**Issue by tepcii** [rinukkusu/spotify-dart#59]
I need to get the search results in Japanese, so I want to add "market=JP" to the parameter.
Is there any way?

**Comment by rinukkusu** [comment]
Do you have a reference for that? I couldn't find anything 😕

**Comment by rinukkusu** [comment]
Defnitely possible - from the [documentation](https://developer.spotify.com/documentation/web-api/reference/search/search/) for reference:

> 
> _Optional._ 
> An [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) or the string `from_token`. If a country code is specified, only artists, albums, and tracks with content that is playable in that market is returned. 
> **Note:** 
> - Playlist results are not affected by the market parameter.
> - If market is set to `from_token`,  and a valid access token is specified in the request header, only  content playable in the country associated with the user account, is  returned. 
> - Users can view the country that is associated with their account in the [account settings](https://www.spotify.com/se/account/overview/). A user must grant access to the `user-read-private` scope prior to when the access token is issued.

**Comment by tepcii** [comment]
Thank you for the quick response!
