### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by stefanoromanello** [rinukkusu/spotify-dart#68]
Hi, I would like to know how to use the refresh token. Currently I can log in and save the credentials but after about 10 minutes the refresh token expires and I need to ask the user another login. Is there a way to ask to the API a new token when the old one expires without asking the login again?

In particular, this is the error I get when I try to create a SpotifyApi class by using the saved credentials:

```
Exception has occurred.
AuthorizationException (OAuth authorization error (invalid_grant): Refresh token revoked.)
```

**Comment by shinyford** [comment]
I'd like to add that the exception above doesn't seem to be able to be caught:

```
try {
    this.api = SpotifyApi(creds);
} on AuthorizationException {
    this.api = null;
}
```
still throws the exception. Would be great to be able to catch the exception, at least.

**Comment by stefanoromanello** [comment]
Thanks for the answer. Yes, this can solve the error but still, I don't get why I have this problem in the first place. The refresh token should get me a new token without a problem and the refresh token is revoked only from the account settings..

**Comment by stefanoromanello** [comment]
Update: at each new token obtained by using the token refresh I get a new token refresh to replace the old one.

**Comment by rinukkusu** [comment]
@stefanoromanello so your immediate problem regarding the refresh token is now fixed?

@shinyford yes, indeed - will add a todo!

**Comment by stefanoromanello** [comment]
> add a todo!

Yes

**Comment by stefanoromanello** [comment]
> @stefanoromanello so your immediate problem regarding the refresh token is now fixed?
> 
> @shinyford yes, indeed - will add a todo!

Yes

**Comment by Diaglyonok** [comment]
@stefanoromanello, so you are not using Saved Credentials Flow? Do you refresh your token manually to save a new refresh token?

**Comment by cosupre** [comment]
Hi everyone,

I would like to get some help. 

I used the sample code from the README to save credentials with SharedPreferences after log in and get SpotifyApi object from SpotifyApiCredentials at each restart/reload of the application
But, if the refreshToken is used to get a new AccessToken, it doesn't replace the data stored in my sharedPreferences by the new accessToken and the new refreshToken . So, when I restart/reload my app, an error in thrown saying the refreshToken is revoked.

 I don't have any idea about what is the best solution to store those credentials and update the saved data each time.
 
 Thanks for your help. Say me if I need to post this in another place
