### ISSUE TITLE
Mixin Classes are not generated.

### ISSUE THREAD

**Issue by hayribakici** [rinukkusu/spotify-dart#8]
Hi,

when I try to let dart build the generated json-serializer code with `pub run build_runner build`, the model classes become erroneous, because all the the `_$...Mixin` classes are not generated. What is the best way to let dart build the mixins as well?

Thanks for this library again:)
cheers

**Comment by rinukkusu** [comment]
Apparently those are not generated/needed anymore - the serializing methods are exposed directly. I fixed that with the [latest commit](https://github.com/rinukkusu/spotify-dart/commit/905feb6d9eb1e5857fcc284a87bb3e060cbc2b7e).

Sorry for the inconvenience :smile_cat:
