### ISSUE TITLE
Fetch an album or list of albums does not return the tracks in the album

### ISSUE THREAD

**Issue by stefanoromanello** [rinukkusu/spotify-dart#82]
From the api https://developer.spotify.com/documentation/web-api/reference-beta/#category-albums Spotify is providing the songs of an album in the playlists but the Album endpoint is not fetching them... Can you include the tracks in the API?

**Comment by rinukkusu** [comment]
Hi @stefanoromanello - can you please check, if this works for you in `0.5.0`?
