### ISSUE TITLE
_$AlbumFromJson is not working when there is releaseDate

### ISSUE THREAD

**Issue by stefanoromanello** [rinukkusu/spotify-dart#84]
I see that the Album class is extending AlbumSimple and is overriding releaseDate and releaseDatePrecision without assigning the value to the superclass. The result of _$AlbumFromJson is so an Album with releaseDate and releaseDatePrecision equals null. 
I suggest removing the override from the Album class.

**Comment by hayribakici** [comment]
@stefanoromanello I agree. The `releaseDate` and `releaseDatePrecision` are not necessary in `Album` as `AlbumSimple` already have them. I created a PR #99 for that.
