### ISSUE TITLE
How long can I leave open the api?

### ISSUE THREAD

**Issue by stefanoromanello** [rinukkusu/spotify-dart#86]
I've currently implemented some background services in my app and it needs to stay always open because for some devices (Xiaomi) the foreground service of android gets killed and even with START_STICKY may take some time to start or not start at all. 

The issue that I'm facing is that if I leave the app open for more than 4/5 hours, I can open it from recent apps (first time) use it normally and then leave it in the background. If I do this again (second time) after 4/5 hours the app works again but if i close it and then re open it asks me to login. 

Currently, my app at startup initialize a new SpotifyBase by providing the credentials obtained from the last login and save the new credentials obtained from the new login (especially the new refresh token) for the next login. 
I do this because from my understanding the refresh token works only one time and when I get a successful login spotify's response contains a new refresh tocken to be used next time.

My supposition is that the API (spotify-dart) is refreshing the access token the first time but it's not saving the new refresh token for the second use.
Can this be the issue? Because I'm not sure..

Note: in all of this if the app is always open than the api works fine. When I close it and then open it after 12 hours of up time the refresh token is expired and it asks me to login

**Comment by stefanoromanello** [comment]
Also, from what I've seen you don't manage the refreshes by using Spotify's token endpoint (https://developer.spotify.com/documentation/general/guides/authorization-guide/ point 4) but by using the oauth2 library.
Is spotfiy-dart using an equivalent implementation? For me, this can cause issues because Spotify requires only the refresh token obtained at the first login and returns only an access token (https://i.imgur.com/0Pj3NI7.png) while your implementation returns a different refresh token at each refresh.

**Comment by stefanoromanello** [comment]
Update:

> My supposition is that the API (spotify-dart) is refreshing the access token the first time but it's not saving the new refresh token for the second use.
> Can this be the issue? Because I'm not sure..

![image](https://user-images.githubusercontent.com/4083715/100237810-b6b1b500-2f2f-11eb-83bb-54987045a2d9.png)

From the[ OAuth library](https://i.imgur.com/mRTrlAR.png), the method get refreshes the access token if it's expired. 
This is a big issue because my app can't save the new refresh code that OAuth obtain from its request.

**Comment by stefanoromanello** [comment]
@rinukkusu  @hayribakici please look at this, I think it's an important case.

**Comment by hayribakici** [comment]
@roisnir could you also take a look at this?

**Comment by roisnir** [comment]
@stefanoromanello 
If there was an onRefresh method of the oauth2 client, so you could save the new token every time it's refreshed. 
Would it be a proper solution?

**Comment by stefanoromanello** [comment]
> @stefanoromanello
> If there was an onRefresh method of the oauth2 client, so you could save the new token every time it's refreshed.
> Would it be a proper solution?

Since 
If it's a method of spotify-dart accessible from my application (i can think of callback functions) then yes for sure,

**Comment by stefanoromanello** [comment]
My provisional code is the following. For SURE you can write better but to give you an idea this is what I'm looking for. 
Ps. I need to test this for a couple of days but the first tests are successful.

added in spotify.dart:
```
SpotifyApi.withCallback(SpotifyApiCredentials credentials, Function(SpotifyApiCredentials) call)
      : super(credentials, http.Client(), call);
static oauth2.AuthorizationCodeGrant authorizationCodeGrantWithCallback(
      SpotifyApiCredentials credentials, Function(SpotifyApiCredentials) call) {
    return SpotifyApiBase.authorizationCodeGrant(credentials, http.Client(), call);
  }
```

changes in spotify_base.dart:

```
static oauth2.AuthorizationCodeGrant authorizationCodeGrant(SpotifyApiCredentials credentials, http.BaseClient httpClient,
      [Function(SpotifyApiCredentials) callBack]) {
    if (callBack == null)
      return oauth2.AuthorizationCodeGrant(credentials.clientId, Uri.parse(SpotifyApiBase._authorizationUrl), Uri.parse(SpotifyApiBase._tokenUrl),
          secret: credentials.clientSecret, httpClient: httpClient);
    else
      return oauth2.AuthorizationCodeGrant(credentials.clientId, Uri.parse(SpotifyApiBase._authorizationUrl), Uri.parse(SpotifyApiBase._tokenUrl),
          secret: credentials.clientSecret, httpClient: httpClient, onCredentialsRefreshed: (oauth2.Credentials cred) {
        SpotifyApiCredentials newCred = SpotifyApiCredentials(credentials.clientId, credentials.clientSecret,
            accessToken: cred.accessToken, expiration: cred.expiration, refreshToken: cred.refreshToken, scopes: cred.scopes);
        callBack(newCred);
      });
  }
```

```
static FutureOr<oauth2.Client> _getOauth2Client(SpotifyApiCredentials credentials, http.BaseClient httpClient,
      [Function(SpotifyApiCredentials) callback]) async {
    if (credentials.fullyQualified) {
      var oauthCredentials = credentials._toOauth2Credentials();

      if (oauthCredentials.isExpired) {
        oauthCredentials = await oauthCredentials.refresh(
          identifier: credentials.clientId,
          secret: credentials.clientSecret,
          httpClient: httpClient,
        );
      }

      if (callback != null)
        return oauth2.Client(
          oauthCredentials,
          identifier: credentials.clientId,
          onCredentialsRefreshed: (oauth2.Credentials cred) {
            SpotifyApiCredentials newCred = SpotifyApiCredentials(credentials.clientId, credentials.clientSecret,
                accessToken: cred.accessToken, expiration: cred.expiration, refreshToken: cred.refreshToken, scopes: cred.scopes);
            callback(newCred);
          },
          secret: credentials.clientSecret,
        );

      return oauth2.Client(
        oauthCredentials,
        identifier: credentials.clientId,
        secret: credentials.clientSecret,
      );
    }
```

And in my code I access the API in the following way:
At the first login I use
```
grant = SpotifyApi.authorizationCodeGrantWithCallback(credentials, (SpotifyApiCredentials newCred) async {
      await await spotify.saveNewCredentials(newCred);
      print("Saved from oauth login" + newCred.refreshToken);
    });
```
Otherwise:
```
SpotifyApi api = SpotifyApi.withCallback(spotifyCredentials, (SpotifyApiCredentials newCred) async {
          await _saveCredentials(newCred);
          print("Saved from oauth" + newCred.refreshToken);
        }); 
```

**Comment by roisnir** [comment]
Looks good!
I don't have much time in the next few weeks, but you are more than welcome to open a PR and we'll review it.
